# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# defaults:
#   run:
#     working-directory: ./app

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # - run: apk add --update rsync
    - run: mkdir -p ~/.ssh
    - run: cp /media/config/.ssh/*  ~/.ssh/
    - run: chmod 0700 ~/.ssh ~/.ssh/*
    - run: echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - run: npm i -g yarn
    # - run: yarn
    # - run: yarn build
    - run: rm -rf node_modules
    - run: rm -rf .git
    - run: rsync -ravO --no-perms --no-g --exclude=".*" . /var/www/planthub/
    - run: cd /var/www/planthub/ && ls
